version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: estapar-postgres
    environment:
      POSTGRES_DB: estapar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  garage-simulator:
    image: cfontes0estapar/garage-sim:1.0.0
    container_name: estapar-garage-simulator
    network_mode: host

volumes:
  postgres_data:
  rabbitmq_data: