micronaut:
  server:
    port: 3003
  application:
    name: estapar-demo
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/resources/webjars/swagger-ui/4.15.5
        mapping: /swagger-ui/**
      public:
        paths: classpath:public
        mapping: /**
  health:
    monitor:
      enabled: true
  openapi:
    views:
      spec: swagger-ui.enabled=true,redoc.enabled=true,rapidoc.enabled=true,swagger-ui.theme=flattop

# OpenAPI configuration
openapi:
  info:
    title: Estapar API
    version: 1.0
    description: API para o sistema Estapar
    contact:
      name: Jackson Valadares
      email: jackson.valadares@ideen.tech
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0
  tags:
    - name: Parking
      description: Parking operations
    - name: Revenue
      description: Revenue operations
    - name: Sectors
      description: Sector management

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/estapar`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES

flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true
      locations:
        - classpath:db/migration

garage-simulator:
  url: ${GARAGE_SIMULATOR_URL:`http://localhost:3000`}
